version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd back/helfit
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename .back/helfit/build/libs/*.jar)
artifacts:
  files:
    - helfit/build/libs/*.jar
    - helfit/scripts/**
    - helfit/appspec.yml
  discard-paths: yes
