version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
artifacts:
  files:
    - build/libs/*.jar
    - scripts/**
    - appspec.yml
  discard-paths: yes
