name: Frontend CI/CD

on:
  push:
    branches: ["dev"]

env:
  APPLICATION_NAME: helfit
  APPLICATION_GROUP_NAME: helfit-group
  S3_BUCKET_NAME: helfit.life
  S3_BUCKET_DIRECTORY: backend
  ZIP_FILE: front-helfit.zip

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: front
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm ci
        run: npm ci

      - name: Run npm run build
        run: npm run build --if-present

      - name: Make zip file
        run: zip -r ./$ZIP_FILE .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws deploy push --application-name $APPLICATION_NAME
             --s3-location s3://$S3_BUCKET_NAME/$ZIP_FILE --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $APPLICATION_NAME 
             --deployment-config-name CodeDeployDefault.OneAtATime 
             --deployment-group-name $APPLICATION_GROUP_NAME 
             --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$ZIP_FILE
